### PR TITLE
Screen two rover feed

### PR DESCRIPTION
**Pull request by DatsIsaiah**
Added media player with youtube video. Had to remove minimap since it kept crashing the server when both tried to be on at the same time.

### CODE REVIEW

**Review by Turfader — CHANGES_REQUESTED** [review]
See Abhi's comments. Make sure to update your documentation with your fixes.

**Review by abhi-arya1 — CHANGES_REQUESTED** [review]
- Hold off until Map Bug is fixed and we know what format the Rover Video Stream will be in 
- Please make the video a *component*, and revert the `page.tsx` file back to its original state, and add in the video component near the map
- Current task: Make this a component, then let us know, then standby for bug fixes.

**Comment by abhi-arya1** [comment]
this will be closed and fixed due to merge conflicts -- PR shouldn't stay open, but itll be accessible in this repo's Pull Requests tab

**Comment by abhi-arya1** [comment]
closed

**Comment by abhi-arya1** [comment]
DO NOT DELETE

**Pull request closed without merging**
