### PR TITLE
updated biometric data format update

### PR DESCRIPTION
**Pull request by ivanvuong**
format update

### CODE REVIEW

**Review by abhi-arya1 — APPROVED** [review]
lgtm--we'll add the actual api endpoint once the vision kits arrive.

**Review by Turfader — APPROVED** [review]
Looks good. Do look into that json formatting issue at some point. Fine for now tho

**Review by abhi-arya1 — CHANGES_REQUESTED** [review]
instead of having the `datatype` query, just make it return a dataset each time.

**Review by ivanvuong — COMMENTED** [review]
made it return a general dataset, font went back to normal, all mixed up now because alphabetical order

**Review by abhi-arya1 — APPROVED** [review]
looks good to me -- approved

**Pull request merged**
